package org.jegrid.impl;

import org.jegrid.NodeAddress;

import java.io.Serializable;

/**
 * Generated by the server in response to an assign message.
 * <br> User: jdavis
 * Date: Oct 7, 2006
 * Time: 11:43:07 AM
 */
public class AssignResponse implements Serializable
{
    private int threadsRemaining;
    private NodeAddress server;
    private boolean accepted;

    public AssignResponse(NodeAddress server, int freeThreads, boolean accepted)
    {
        this.server = server;
        this.threadsRemaining = freeThreads;
        this.accepted = accepted;
    }

    public int getThreadsRemaining()
    {
        return threadsRemaining;
    }

    public NodeAddress getServer()
    {
        return server;
    }

    public String toString()
    {
        return "AssignResponse{" +
                "threadsRemaining=" + threadsRemaining +
                ", server=" + server +
                ", accepted=" + accepted +
                '}';
    }

    public boolean accepted()
    {
        return accepted;
    }
}
